export const todaDesignSystem = {
  name: "Toda 모바일 디자인 시스템",
  productArchetype: "조용하고 빠른 모바일 기록 도구",
  principles: [
    "variant는 도메인 값이 아니라 UI 속성으로 정의한다.",
    "모바일에서 먼저 읽히는 텍스트, 간격, 터치 영역을 기본값으로 삼는다.",
    "컴포넌트는 size, tone, emphasis, density, surface, state 축으로 확장한다.",
    "도메인 예시는 샘플 콘텐츠로만 다루고 공통 컴포넌트 API에는 넣지 않는다.",
  ],
  variantAxes: [
    {
      name: "size",
      values: ["sm", "md", "lg"],
      use: "터치 영역, 텍스트 크기, 컨트롤 높이의 물리적 크기",
    },
    {
      name: "tone",
      values: ["neutral", "accent", "success", "danger"],
      use: "의미 색상. 제품 도메인이 아니라 인터페이스 피드백을 표현한다.",
    },
    {
      name: "emphasis",
      values: ["primary", "secondary", "subtle"],
      use: "사용자가 지금 봐야 할 행동의 시각 우선순위",
    },
    {
      name: "density",
      values: ["compact", "comfortable", "spacious"],
      use: "동일 컴포넌트의 정보 밀도와 여백",
    },
    {
      name: "surface",
      values: ["canvas", "raised", "glass", "inset"],
      use: "캔버스, 패널, 임시 표면, 눌린 표면의 깊이",
    },
    {
      name: "state",
      values: ["default", "selected", "disabled", "loading", "open"],
      use: "상호작용 중인 상태를 일관되게 표현한다.",
    },
  ],
  foundations: {
    color: [
      { name: "Canvas", token: "--ds-surface-canvas" },
      { name: "Raised", token: "--ds-surface-raised" },
      { name: "Glass", token: "--ds-surface-glass" },
      { name: "Accent", token: "--ds-accent" },
      { name: "Success", token: "--ds-success" },
      { name: "Danger", token: "--ds-danger" },
    ],
    spacing: [
      { name: "1", token: "--ds-space-1", value: "0.25rem" },
      { name: "2", token: "--ds-space-2", value: "0.5rem" },
      { name: "3", token: "--ds-space-3", value: "0.75rem" },
      { name: "4", token: "--ds-space-4", value: "1rem" },
      { name: "6", token: "--ds-space-6", value: "1.5rem" },
      { name: "8", token: "--ds-space-8", value: "2rem" },
    ],
    typography: [
      { name: "Display", token: "--ds-type-display", use: "화면 대표 제목" },
      { name: "Title", token: "--ds-type-title", use: "섹션 제목" },
      { name: "Body", token: "--ds-type-body", use: "기본 설명과 입력" },
      { name: "Caption", token: "--ds-type-caption", use: "보조 라벨" },
    ],
    radius: [
      { name: "Small", token: "--ds-radius-sm" },
      { name: "Medium", token: "--ds-radius-md" },
      { name: "Large", token: "--ds-radius-lg" },
      { name: "XL", token: "--ds-radius-xl" },
    ],
  },
  componentRoadmap: [
    "Text",
    "Stack",
    "Cluster",
    "Grid",
    "Divider",
    "Badge",
    "TokenSwatch",
    "SpacingScale",
    "Avatar",
    "AppBar",
    "PageHeader",
    "PillTabs",
    "BottomTabBar",
    "NoticeBanner",
    "ListItem",
    "MetricCard",
    "AnimatedNumber",
    "ActionGrid",
    "Button",
    "IconButton",
    "SegmentedControl",
    "SwitchControl",
    "FloatingActionButton",
    "ChatBubble",
    "MessageInput",
    "Surface",
    "BottomSheet",
    "CalendarPreview",
    "ThreeStageSheet",
    "MenuCheckboxGroup",
  ],
} as const

export type TodaDesignSystem = typeof todaDesignSystem
